repos:
- repo: local
  hooks:
  - id: cargo-fmt
    name: Format Rust code
    entry: cargo fmt
    language: system
    types: [rust]
    pass_filenames: false

  - id: cargo-clippy
    name: Lint Rust code
    entry: cargo clippy
    language: system
    types: [rust]
    pass_filenames: false
    args: [--all-targets, --all-features, --, -D, warnings]

  - id: cargo-test
    name: Run Rust tests
    entry: cargo test
    language: system
    types: [rust]
    pass_filenames: false
    stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-merge-conflict
  - id: check-case-conflict
